# snap/snapcraft.yaml
# Copyright (C) 2019 Kaz Nishimura
#
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and
# this notice are preserved.  This file is offered as-is, without any warranty.
---
name: xllmnrd
title: XLLMNRD
base: core18
version: "2.1.0"
summary: Link-Local Multicast Name Resolution (LLMNR) responder daemon
description: |
  XLLMNRD is a Link-Local Multicast Name Resolution (LLMNR) responder daemon.

  This program makes your Linux-based server accessible by name from modern Windows computers on the same LAN.
license: GPL-3.0
confinement: strict
grade: stable
apps:
  responder:
    command: xllmnrd
    daemon: forking
    plugs:
      - network
      - network-bind
parts:
  xllmnrd:
    plugin: autotools
    source: https://bitbucket.org/kazssym/xllmnrd/downloads/xllmnrd-2.1.tar.gz
    source-checksum: sha256/842322ac94e7fa832e5942ef790a964d80c040c1281ecdbaf88a91fd7674c7f5
