# snap/snapcraft.yaml
# Copyright (C) 2019 Kaz Nishimura
#
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and
# this notice are preserved.  This file is offered as-is, without any warranty.
---
name: xllmnrd
title: XLLMNRD
base: core
version: "3.0.0"
summary: Link-Local Multicast Name Resolution (LLMNR) responder daemon
description: |
  XLLMNRD is a Link-Local Multicast Name Resolution (LLMNR) responder daemon.

  This program makes your Linux-based server accessible by name from modern Windows computers on the same LAN.
license: GPL-3.0
confinement: strict
grade: devel
apps:
  responder:
    command: xllmnrd
    daemon: forking
    plugs:
      - network
      - network-bind
parts:
  xllmnrd:
    plugin: autotools
    source: https://bitbucket.org/kazssym/xllmnrd/downloads/xllmnrd-3-alpha.1.tar.gz
    source-checksum: sha256/4bbbfabd51f21d57cc088f739e22dd74c0b703bce1e3433eca1aa80163862c38
    build-packages:
      - g++
