# snap/snapcraft.yaml
# Copyright (C) 2019 Kaz Nishimura
#
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and
# this notice are preserved.  This file is offered as-is, without any warranty.
---
name: xllmnrd
title: Xenium LLMNR Responder
base: core18
version: "3.0.0"
summary: Link-Local Multicast Name Resolution (LLMNR) responder daemon
description: |
  Xenium LLMNR Responder (xllmnrd) is an IPv6 network service daemon
  that responds to name queries from Microsoft Windows computers on the same
  network link so that you can get the IPv6 addresses of the server *without
  any DNS configuration*.  It effectively supplements IPv4-only NetBIOS name
  resolution typically provided by Samba.

  This program implements Link-Local Multicast Name Resolution (LLMNR) as
  described in RFC 4795.

  Note this program has no UI.
license: GPL-3.0
confinement: strict
grade: devel
apps:
  responder:
    command: xllmnrd
    daemon: forking
    plugs:
      - network
      - network-bind
parts:
  xllmnrd:
    plugin: autotools
    source: https://bitbucket.org/kazssym/xllmnrd/downloads/xllmnrd-3.0.tar.gz
    source-checksum: sha256/330d1e5d9f4699e255052410ff6e2b225329000fbf260c86287dbb1bba780306
    build-packages:
      - g++
      - gettext
      - pkg-config
