# snap/snapcraft.yaml
# Copyright (C) 2019 Kaz Nishimura
#
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and
# this notice are preserved.  This file is offered as-is, without any warranty.
---
name: xllmnrd
title: Xenium LLMNR Responder
version: "4.0.0"
summary: Link-Local Multicast Name Resolution (LLMNR) responder daemon
description: |
  Xenium LLMNR Responder (xllmnrd) is an IPv6 network service daemon
  that responds to name queries from Microsoft Windows computers on the same
  network link so that you can get the IP addresses of the server *without
  any DNS configuration*.  It effectively replaces an IPv4-only NetBIOS name
  resolution responder typically provided by Samba.

  This program implements Link-Local Multicast Name Resolution (LLMNR) as
  described in RFC 4795.

  Note this program has no UI.
license: GPL-3.0+
confinement: strict
grade: stable
base: core18
icon: icon.png
apps:
  responder:
    command: xllmnrd
    daemon: forking
    plugs:
      - network
      - network-bind
    environment:
      LC_ALL: C.UTF-8
parts:
  xllmnrd:
    plugin: autotools
    source: https://bitbucket.org/kazssym/xllmnrd/downloads/xllmnrd-4.0.tar.gz
    source-checksum: sha256/526efaf84e5daec16a7de7ca43256e4d7761acfe967817345ee6e333e1a548be
    build-packages:
      - g++
      - gettext
      - pkg-config
