# snap/snapcraft.yaml
# Copyright (C) 2019 Kaz Nishimura
#
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and
# this notice are preserved.  This file is offered as-is, without any warranty.
---
name: xllmnrd
title: XLLMNRD
base: core
version: "2.0.1"
summary: Link-Local Multicast Name Resolution (LLMNR) responder daemon
description: >
  XLLMNRD is a Link-Local Multicast Name Resolution (LLMNR) responder daemon.
license: GPL-3.0
confinement: strict
grade: devel
apps:
  responder:
    command: xllmnrd
    daemon: forking
    plugs:
      - network
      - network-bind
parts:
  xllmnrd:
    plugin: autotools
    source: https://bitbucket.org/kazssym/xllmnrd/downloads/xllmnrd-2.0.tar.gz
    source-checksum: sha256/2fdba0d03d23875652b14bee8fdbd4cd86dba74e59e37ab03b2d43d3eb2697f4
    override-pull: |
      snapcraftctl pull
      rm build-aux/config.guess
      cp /usr/share/libtool/build-aux/config.guess build-aux/config.guess
